apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb 
          image: mongo:5.0.12
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets 
                  key: mongo-root-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets 
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-services
spec:
  selector:
    app: mongodb 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
